### ISSUE TITLE
Minificar todos los ficheros

### ISSUE THREAD

**Issue by eduescal13** [alu0100825985/mocha-y-chai-edu-daniel#1]
En el siguiente commit 7548cf78a4086c65499f44c28db7b60f303b005e reflejas que has minificado todos los archivos, pero existen algunos dentro del directorio **vendor** que siguen igual, ¿no crees que deberías minificarlos también?

**Comment by alu0100825985** [comment]
Tienes razón, me han quedado algunos ficheros como mocha.js sin minificar. En breve lo aplico.
¡Muchas gracias por la aclaración!
